import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

// NexFlow KB · full platform manifest
// Returns the latest snapshot of every page in the platform — route, file,
// title, imports, and which APIs each page calls. Used by Rizz and any
// contributor tooling that needs a structured map of the codebase.
// Data is regenerated by NexFlow weekly and committed at /nexflow.manifest.json.
export async function GET() {
  try {
    const manifestPath = path.join(process.cwd(), 'nexflow.manifest.json');
    if (!fs.existsSync(manifestPath)) {
      return NextResponse.json({ error: 'manifest not yet generated' }, { status: 503 });
    }
    const raw = fs.readFileSync(manifestPath, 'utf-8');
    const data = JSON.parse(raw);
    return NextResponse.json(data, {
      headers: {
        'Cache-Control': 'public, s-maxage=300, stale-while-revalidate=3600',
        'Access-Control-Allow-Origin': '*',
      },
    });
  } catch (err) {
    return NextResponse.json({ error: 'failed to load manifest' }, { status: 500 });
  }
}
